FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    udev \
    systemd-sysv \
    openssh-server \
    iproute2 \
    curl \
    nfs-common \
    haveged \
    tzdata \
    nodejs \
    npm \
    python3 \
    python3-pip \
    python3-venv \
    wget \
    apt-transport-https \
    software-properties-common \
    libatomic1 \
    shellcheck \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
  
# Install golang
ENV GO_VERSION=1.26.5
RUN wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
  && rm -rf /usr/local/go \
  && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
  && rm go${GO_VERSION}.linux-amd64.tar.gz \
  && echo 'export PATH="$PATH:/usr/local/go/bin"' >> ~/.bashrc  

# Install GitHub cli
RUN (type -p wget >/dev/null || (apt-get update && apt-get install wget -y)) \
  && mkdir -p -m 755 /etc/apt/keyrings \
  && out=$(mktemp) \
  && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
  && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
  && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
  && mkdir -p -m 755 /etc/apt/sources.list.d 	\
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    gh \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Claude Code terminal
RUN curl -fsSL https://claude.ai/install.sh | bash \
  && echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc

# Install pnpm
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -

COPY files/install-docker.sh /root/scripts/install-docker.sh
# RUN chmod 755 /root/scripts/install-docker.sh
